openapi: 3.0.0
info:
  title: User Service API
  version: 1.0.0
  description: API documentation for User Service.
servers:
  - url: http://127.0.0.1:5001
paths:
  /api/users/register:
    post:
      summary: Register a new user
      description: Creates a new user account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User registered successfully.
        '400':
          description: Invalid input.

  /api/users/login:
    post:
      summary: Login and get an access token
      description: Authenticates the user and returns a JWT token if credentials are correct.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "user@example.com"
                password:
                  type: string
                  example: "securepassword"
      responses:
        '200':
          description: Successful login with JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  access_token:
                    type: string
        '400':
          description: Missing email or password
        '401':
          description: Invalid password
        '404':
          description: User not found
  
  /api/users/profile:
    get:
      summary: View the profile of the logged-in user
      description: Retrieves the profile information (name, email, role) of the authenticated user.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully retrieved user profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
                  role:
                    type: string
        '404':
          description: User not found
        '401':
          description: Unauthorized - Token is missing or invalid

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT